sqlite: &sqlite
  adapter: sqlite3
  database: db/registro.sqlite3

mysql: &mysql
  adapter: mysql2
  username: travis
  database: registro
 
postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: registro
  min_messages: ERROR

home: &home
  adapter: mysql2
  username: root
  password: password
  database: registro

default: &default
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "home" %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: registro
  username: root
  password: password
