default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: registro

test:
  <<: *default
  database: registro_test

production:
  <<: *default
  database: registro
  username: root
  password: password
