default: &default
  adapter: mysql2
  encoding: utf8
  username: travis  

development:
  <<: *default
  database: registro

test:
  <<: *default
  database: registro_test

production:
  <<: *default
  database: registro
  username: root
  password: password
